name: Test and Lint
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.**
  workflow_call:
jobs:
    tsc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run lib:tsc
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run lib:lint
